name: Auto Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Source Code
        uses: actions/checkout@v4

      - name: Set Up Java (Wajib untuk APK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Reset & Rebuild Folder Android (Biar Fresh V2)
        run: |
          rm -rf android
          flutter create . --platforms=android

      - name: Ambil Dependencies App
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Simpan APK Berhasil ke Lampiran (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Katalog-Release
          path: build/app/outputs/flutter-apk/app-release.apk
